# Generated by Django 4.2.5 on 2023-11-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('sitting_capacity', models.PositiveIntegerField()),
                ('mileage', models.FloatField()),
                ('fuel_amount', models.FloatField()),
                ('activeness', models.CharField(choices=[('active', 'Active'), ('non_active', 'Non-Active')], default='active', max_length=20)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='auction_images/')),
                ('status', models.CharField(choices=[('not_sold', 'Not Sold'), ('sold', 'Sold')], max_length=20)),
                ('information', models.TextField()),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='vehicles.vehicle')),
            ],
        ),
    ]
