# Generated by Django 4.2.5 on 2023-11-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='activeness',
            field=models.CharField(choices=[('active', 'Active'), ('non_active', 'Non-Active')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
