# Generated by Django 4.2.5 on 2023-11-25 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('government_id', models.CharField(max_length=20)),
                ('driving_license_code', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_position', models.CharField(max_length=255)),
                ('end_position', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('awaiting', 'Awaiting'), ('active', 'Active'), ('canceled', 'Canceled'), ('delayed', 'Delayed'), ('completed', 'Completed')], max_length=20, null=True)),
                ('assigned_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_routes', to='drivers.driver')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
