# Generated by Django 4.2.5 on 2023-11-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='status',
            new_name='status_route',
        ),
    ]
