# Generated by Django 4.2.5 on 2023-11-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_rename_status_route_status_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='assigned_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to='drivers.driver'),
        ),
    ]
