# Generated by Django 4.2.5 on 2023-11-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_route_assigned_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='latitude',
            field=models.FloatField(default=40.04),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='longitude',
            field=models.FloatField(default=56.58),
            preserve_default=False,
        ),
    ]
